app/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'accounts.views.homepage', name='home'),
    url(r'^signup/$', 'accounts.views.signup', name='signup'),
    url(r'^login/$', 'accounts.views.login', name='login'),   
    url(r'^logout/$', 'accounts.views.logout', name='logout'),   
    url(r'^requests/$', 'accounts.views.project_requests', name='project_requests'),   

    
    # Projects
    url(r'^projects/create/$', 'mentorships.views.project_form', name='project_form'),
    url(r'^projects/$', 'mentorships.views.projects', name='project_category'),
    url(r'^projects/skill/(?P<skill_id>[0-9]+)/$', 'mentorships.views.projects', name='project_category_skill'),       
    url(r'^projects/(?P<project_id>[0-9]+)/supporters/$', 'accounts.views.sponsor', name='sponsor'),   
    url(r'^projects/(?P<project_id>[0-9]+)/support/$', 'mentorships.views.support', name='project_support'),   
    url(r'^projects/(?P<project_id>[0-9]+)/edit/$', 'mentorships.views.project_form', name='project_edit'),
    url(r'^projects/(?P<project_id>[0-9]+)/$', 'mentorships.views.projects', name='project_detail'),   
    url(r'^projects/(?P<project_id>[0-9]+)/log/$', 'mentorships.views.project_log', name='project_log'),   
    
    url(r'^profile/edit/$', 'accounts.views.profile_form', name='profile_form'),   
    
    url(r'^admin/', include(admin.site.urls)),
)

app/mentorships/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.template.loader import render_to_string

from lib.utils import shorten_url
from accounts.models import Skill

class Project(models.Model):
    PROJECT_TYPE_CHOICES = (
            ('m', 'Mentoring'),
            ('l', 'Looking for Mentors')
        )
    added_by = models.ForeignKey(User)
    skills = models.ManyToManyField(Skill)
    description = models.TextField(max_length=1000)
    title = models.CharField(max_length=120)
    looking_for = models.TextField(max_length=1000)
    project_type = models.CharField(max_length=1, choices=PROJECT_TYPE_CHOICES, default="l")
    members = models.ManyToManyField(User, null=True, blank=True, related_name="members")
    closed = models.BooleanField(default=False)

    class Meta:
        ordering = ('-id',)

    def __unicode__(self):
        return self.title

    @property
    def share_url(self):
        url = settings.SERVER_SCHEME_AND_NETLOC + '/projects/' + str(self.id) + '/supporters'
        return shorten_url(url)

class JoinRequest(models.Model):
    added_by = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    note = models.TextField(max_length=1000)
    closed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.project.title

    def send_notification(self):
        '''Send a notification to the user'''
        subject = "%s is interested in your mentorship project" % self.added_by.first_name
        message = render_to_string('email/project_request.html', {'join_request': self})
        self.project.added_by.send_email(subject, message)

    def accept(self):
        '''Add the requestor to the project member team
        and send a notification'''
        self.closed = True
        self.save()
        project = self.project
        project.members.add(self.added_by)
        project.save()
        # Send notification to the requestor
        subject = "You have been accepted into %s's project" % self.project.added_by.first_name
        message = render_to_string('email/project_request_accept.html', {'project': self.project})
        self.added_by.send_email(subject, message)
        # Send notification to the project leader
        leader_subj = "%s has joined your project. Introduce yourself." % self.added_by.first_name
        leader_message = render_to_string('email/introduction.html', {'new_member': self.added_by, 'project': self.project})
        self.project.added_by.send_email(leader_subj, leader_message)

    @property
    def status(self):
        if self.added_by in self.project.members.all():
            return 'Accepted'
        elif self.closed == True:
            return 'Rejected'
        return 'Pending'

class ProjectLog(models.Model):
    '''Describes progress of an established mentorship'''
    project = models.ForeignKey(Project)
    content = models.TextField(max_length=1000)
    added_by = models.ForeignKey(User)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-id',)

    def __unicode__(self):
        return self.project.title

class Sponsor(models.Model):
    project = models.ForeignKey(Project)
    email = models.EmailField()
    receive_email_updates = models.BooleanField(default=True)

    def __unicode__(self):
        return self.mentorship_request.from_user.first_name

app/mentorships/forms.py
from django import forms

from mentorships.models import JoinRequest, Project, ProjectLog

class JoinRequestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(JoinRequestForm, self).__init__(*args, **kwargs)
        self.fields['note'].label = "Write them a note about why you're interested"
    
    class Meta:
        model = JoinRequest
        exclude = ('added_by', 'closed', 'project')

class ProjectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['skills'].help_text = "Start typing a skill and hit the tab key."
        self.fields['project_type'].help_text = "Select whether you are looking for a mentor or want to mentor someone."
    
    class Meta:
        model = Project
        fields = (
                'project_type',
                'description', 
                'title', 
                'skills', 
                'looking_for'
            )
        exclude = ('added_by', 'members')

class ProjectLogForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectLogForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = ""
    class Meta:
        model = ProjectLog
        exclude = ('added_by', 'project')

app/mentorships/views.py
from django.views.generic.simple import direct_to_template
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

import json

from mentorships.models import \
        JoinRequest, Project, ProjectLog
from accounts.models import Skill
from mentorships.forms import ProjectForm, ProjectLogForm

@login_required
def project_form(request, project_id=None):
    if bool(project_id):
        project = get_object_or_404(Project, pk=project_id)
        if not project.added_by == request.user:
            return redirect('login')
        edit = True
    else:
        project = None
        edit = False
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            project = form.save(commit=False)
            project.added_by = request.user
            project.save()
            form.save_m2m()
            saved = True
            if not edit:
                return redirect('project_support', project.id)
    return direct_to_template(request, 'project_form.html', locals())

@login_required
@csrf_exempt
def projects(request, project_id=None, skill_id=None):
    '''View for handling mentorship request category and detail views'''
    if request.method == 'POST':
        note = request.POST['note']
        user = request.user
        project = Project.objects.get(pk=project_id)
        join, created = JoinRequest.objects.get_or_create(
                project = project,
                added_by = user,
                note = note)
        if created:
            join.send_notification()
        resp = {'message': 'created'}
        return HttpResponse(json.dumps(resp), mimetype='json')
    if bool(project_id):
        project = get_object_or_404(Project, pk=project_id)
        return direct_to_template(
                request, 'mentorship_detail.html', locals())
    projects = Project.objects.filter(
            closed=False).select_related(
                    'sponsor_set', 'added_by')
    params = request.GET
    if params.get('my_projects'):
        skill = {'name': 'My Projects'}
        projects = projects.filter(added_by=request.user)
    if params.get('mentor'):
        skill = {'name': 'Mentoring'}
        projects = projects.filter(project_type='m')
    if params.get('learner'):
        skill = {'name': 'Learning'}
        projects = projects.filter(project_type='l')
    if bool(skill_id):
        skill = Skill.objects.get(pk=skill_id)
        projects = projects.filter(skills=skill)
    skills = Skill.objects.all()
    return direct_to_template(request, 'mentorship_category.html', locals())

@login_required
def support(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return direct_to_template(request, 'get_supporters.html', locals())

@login_required
def project_log(request, project_id):
    '''Once a mentorship is established, periodic updates
    track the progress of the mentor -> student relationship'''
    mentorship = Project.objects.get(pk=project_id)
    # TODO handle callback from notifications API
    form = ProjectLogForm()
    if request.method == 'POST':
        form = ProjectLogForm(request.POST)
        if form.is_valid():
            log = form.save(commit=False)
            log.added_by = request.user
            log.project = mentorship
            log.save()
            saved = True
            form = ProjectLogForm()
    if request.user == mentorship.added_by:
        role = "learning"
    else:
        role = "mentoring %s on" % mentorship.added_by.first_name
    updates = ProjectLog.objects.filter(project=mentorship)
    return direct_to_template(request, 'mentorship_log.html', locals())

app/mentorships/templates/mentorship_category.html
{% extends "base.html" %}
{% load pagination_tags %}
{% load url_tags %}
{% block content_title %}
Projects
{% if skill %} - {{skill.name}}{% endif %}
{% endblock %}

{% block content %}
{% block instructions %}
<p>Select a project request to connect with a student.
Click "Learn More" to view the <br/>full project application.
Click "Connect" to start mentoring a student!
</p>
{% endblock %}
<div id="connectModal" class="reveal-modal">
    <h1>Join this Project</h1>
    <p>Once you are accepted we will connect you with the 
    project leader you can start collaborating. </p>
    <div id="alert" class="alert-box error" style="display: none;"></div>
    <form>
        <textarea id="note" placeholder="Add a note about why you would like to join"></textarea>
    </form>
    <a class="nice radius large blue button accept">Send Request</a>
    <a class="close-reveal-modal">&#215;</a>
</div>
<div class="row">
    <div class="three columns">
        {% block sidebar %}
        <dl class="nice vertical tabs">
            <dd><a href="{% url project_category %}">Latest</a></dd>
            <dd><a href="{% url project_category %}?my_projects=true">My Projects</a></dd>
            <dd><a href="{% url project_category %}?mentor=true">Mentoring</a></dd>
            <dd><a href="{% url project_category %}?learner=true">Learning</a></dd>
        </dl>
        {% endblock %}
    </div>
    <div class="nine columns">
        {% block detail_content %}
        <p>
            <b>Filter By Skill</b>:
            <select id="skillSelect" style="width: 250px;">
                <option></option>
                {% for skill in skills %}
                <option value="{{skill.id}}">{{skill.name}}</option>
                {% endfor %}
            </select>
        </p>
        {% autopaginate projects 10 %}
        {% for project in projects %}
        <div class="snippet">
            <a 
                href="{% url project_detail project.id %}" 
                class="nice radius small blue button" 
                style="float: right; margin-right: 10px;">
                Lean more »
            </a>
            {% if project.added_by == request.user %}
            <a
                href="{% url project_edit project.id %}"
                class="nice radius small blue button"
                style="float:right; margin-right: 10px">
                Edit » 
            </a>
            {% endif %}
            <p>
                {% with project.added_by as user %}
                <img src="{{user.p2puprofile.picture}}" class="profilepicture small"/>                
                <span>
                    {{user.first_name}} {{user.last_name}}
                    is {% if project.project_type == 'l' %}looking for mentors{% else %}mentoring{% endif %}
                </span>
                {% endwith %}
            </p>
            <h2>{{project.title}}</h2>
            <p>{{project.description|truncatewords:"30"}}</p>
            <b>Skills:</b>
            <p>
            {% for skill in project.skills.all %}
                <span class="tag">
                    <a href="{% url project_category_skill skill.id %}">{{skill.name}}</a>
                </span>
            {% endfor %}
            {% if project.sponsor_set.count > 0 %}
                <img src="/static/images/supporters.png" style="margin-right: 10px;" />
                <b>{{project.sponsor_set.count}} supporters</b>
            {% endif %}
        </div>
        {% empty %}
        <i>No new projects.</i>
        {% endfor %}
        {% paginate %}
        {% endblock %}
    </div>
</div>
{% endblock %}
{% block scripts %}
<link rel="stylesheet" href="/static/stylesheets/select2.css"></script>
<script type="text/javascript" src="/static/javascripts/select2.js"></script> 
<script>
    $(document).ready(function(){ 
        $("#skillSelect").select2({
            placeholder: "Select a skill"
        });
        $("select").on("change", function(e){
            console.log(e);
            window.location =  "{% server_scheme_and_netloc %}" + "/projects/" + "skill/" + e.currentTarget.value;
        });
    });
</script>
{% endblock %}

app/mentorships/templates/mentorship_detail.html
{% extends "mentorship_category.html" %}
{% load pagination_tags %}
{% block content_title %} 
{{project.title}}
{% endblock %}
{% block instructions %}
{% if project.closed %}
<div class="alert-box error">This project is no longer accepting mentors or learners</div>
{% endif %}
<a style="position: absolute; top:0;" href="{% url project_category %}">« Back</a>
{% endblock %}

{% block sidebar %}
<p><img src="{{project.added_by.p2puprofile.picture}}" class="profilepicture large" /></p>
<h3>About {{project.added_by.first_name}}</h3>
{% with project.added_by.p2puprofile as profile %}
<p class="smaller">{{profile.bio|striptags}}</p>
<small>
    <p><b>Location</b>: {{profile.location}}<br/>
    <b>Language</b>: {{profile.language}}
    </p>
</small>
{% endwith %}
<h3>Skills</h3>
{% for skill in project.added_by.p2puprofile.skills.all %}
    <span class="tag">
        <a href="{% url project_category_skill skill.id %}">{{skill.name}}</a>
    </span>
{% endfor %}
{% endblock %}

{% block detail_content %}
{% if not project.closed %}  
<div class="alert-box">
    {% if project.project_type == 'l' %}
    <span>Get started mentoring this student!</span>
    <a 
        class="nice radius blue button connect" 
        style="margin-left: 10px;" 
        data-user-id="{{project.added_by.p2puprofile.p2pu_id}}"
        data-project-request-id="{{project.id}}">
        Mentor {{project.added_by.first_name}} » </a>
    {% else %}
    <span>Join this project and get mentored!</span>
    <a 
        class="nice radius blue button connect" 
        style="margin-left: 10px;" 
        data-user-id="{{project.added_by.p2puprofile.p2pu_id}}"
        data-project-request-id="{{project.id}}">
        Join this project » </a>
    {% endif %}
</div>
{% endif %}
{% if project.sponsor_set.count > 0 %}
<p>
    <img src="/static/images/supporters.png" style="margin-right: 10px;" />
    <b>{{project.sponsor_set.count}} supporters</b>
</p>
{% endif %}
<h2>About the Project</h2>
<p><b>Looking for: </b>{% if project.project_type == 'l' %} Mentors{% else %}Learners{% endif %}</p>
<p>{{project.description}}</p>
<h2>Skills Being Used</h2>
<p>
{% for skill in project.skills.all %}
    <span class="tag">
        <a href="{% url project_category_skill skill.id %}">{{skill.name}}</a>
    </span>
{% empty %}
<i>No skills listed</i>
{% endfor %}
</p>
<h2>Looking For</h2>
<p>{{project.looking_for}}</p>
{% if not project.closed %}  
    {% if project.project_type == 'l' %}
    <a class="nice radius blue button connect">
        Mentor {{project.added_by.first_name}} » 
    </a>
    {% else %}
    <a class="nice radius blue button connect">
        Join this project » 
    </a>
    {% endif %}
{% endif %}
<br/><br/>
{% include "project_log.html" %}
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="/static/javascripts/jquery.reveal.js"></script>
<script type="text/javascript" src="/static/javascripts/project.js"></script>
{% endblock %}

app/mentorships/templates/mentorship_log.html
{% extends "project_form.html" %}
{% load pagination_tags %}
{% block form_title %}Update Progress{% endblock %}
{% block form %}
{% if saved %}
    <div class="alert-box success">Saved!</div>
    <div class="alert-box success">+ Your mentorship rating went up, woohoo!</div>
{% endif %}
<form method="post" action="{% url project_log mentorship.id %}">
    <label>What have you done towards the project "{{mentorship.title}}"?
    {% csrf_token %}
    {{form}}
    <input type="submit" class="nice radius blue button" value="Save" />
</form>
{% endblock %}
{% block fullwidth %}
<div class="container">
    {% include "project_log.html" %}
</div>
{% endblock %}

app/mentorships/templates/project_form.html
{% extends "form_template.html" %}
{% block form_title %}
{% if edit %}
Edit Project
{% else %}Create a Project
{% endif %}
{% endblock %}
{% block form %}
<p>Create a project you are working on or would like to 
work on. Other members will be able to request to join 
your project as a mentor or a student.</p>
{% if saved %}
<div class="alert-box success">Saved!</div>
{% endif %}
<form method="post" action="{% if edit %}{% url project_edit project.id %}{% else %}{% url project_form %}{% endif %}">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Save" class="nice radius large blue button"></input>
    <a href="{% url project_category %}" style="margin-left: 10px;">skip</a>
</form>
{% endblock %}
{% block scripts %}
<link rel="stylesheet" href="/static/stylesheets/select2.css"></script>
<script type="text/javascript" src="/static/javascripts/select2.js"></script> 
<script>
    $(document).ready(function(){ 
        $("#id_skills").select2({
            placeholder: "Select a skill"
        });
        $("#id_project_type").select2({
            placeholder: "Select one"
        });
    });
</script>
{% endblock %}

app/mentorships/templates/project_log.html
{% load pagination_tags %}
{% if project.projectlog_set.all %}
<h2>Progress</h2>
{% autopaginate project.projectlog_set.all 10 %}
{% for update in project.projectlog_set.all %}
<div class="row update">
    <div class="two columns">
        <img class="profilepicture medium" src="{{update.added_by.p2puprofile.picture}}" />
    </div>
    <div class="ten columns">
        <small>{{update.date_added|date}}</small>
        <p>{{update.content}}</p>
    </div>
</div>
<hr style="margin: 0; margin-top:-2px; padding-left: 30px;"/>
{% endfor %}
{% paginate %}
{% endif %}